# Generated by Django 4.0.4 on 2022-05-13 18:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('processo', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('situacao', models.CharField(max_length=50)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
