# Generated by Django 4.0.4 on 2022-05-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_api_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
