# Generated by Django 4.0.4 on 2022-05-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processo', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('situacao', models.CharField(max_length=50)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
